# Sub Stack
## architecture-framework-mbackend-service-b

service: ${self:custom.baseDomain}-${self:custom.subDomain}-service-b

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2
  memorySize: 256
  logRetentionInDays: 14
  apiGateway: ${file(conf/resources/api-gateway.yml)}
  deploymentBucket:
    name: ${self:custom.currentVars.bucketName}
    serverSideEncryption: AES256
  deploymentPrefix: ${self:custom.baseDomain}-${self:custom.subDomain}
  tags: ${file(conf/tags.yml)}

custom: ${file(conf/configs.yml)}

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-package-external

package:
  include:
    - ../../../node_modules

functions:
  healthCheck:
    handler: functions/healthcheck.handler
    events:
      - http:
          path: healthcheck
          method: get
          cors: true
    environment:
      baseDomain: ${self:custom.baseDomain}
      subDomain: ${self:custom.subDomain}
      service: 'service-b'